#configs/generator/sam_generator.yaml
_target_: sam2.automatic_mask_generator.SAM2AutomaticMaskGenerator

defaults:
  - prompt_mode: efficient # TODO: change to efficient   
  - crop_mode: uniform # TODO: change to efficient
  - _self_

model: ??
number_of_points: 10 # number of points to use to prompt sam, if grid mode is selected √ is computed and the output rounded 
points_per_batch: 16 # inner batch size of the mask generator
pred_iou_thresh: 0.0 # threshold over model's predicted mask quality  
stability_score_thresh: 0.7 # filter over the IoU of the masks
stability_score_offset: 0.7
mask_threshold: 0.0 # threshold for mask logits
post_processing_method: mm # nms, bm or none
post_processing_thresh: 0.8 # box IoU cutoff used by nms
use_psr: false # use post process small regions
crop_n_layers: 0 # number of layers of crops
crop_overlap_ratio: 0.33 
crop_n_points_downscale_factor: 2 
point_grids: null # pre-computed points grid if needed
min_mask_region_area: 25.0 # removes holes in masks with area smaller than 
output_mode: binary_mask 
use_m2m: false
cut_edges_masks: true 
multimask_output: true 