#_target_: cuml.cluster.HDBSCAN
_target_: hdbscan.hdbscan_.HDBSCAN
min_cluster_size: 75 # best:75 best cropping: 40
min_samples: 10 # best:5
cluster_selection_epsilon: 0.0
max_cluster_size: 1024
metric: 'precomputed'
alpha: 1.0
cluster_selection_method: 'eom'
allow_single_cluster: false 