#configs/generator/mode/efficient.yaml
name: efficient

defaults:
  - logger: prs_logger
  - cluster_alg: no_crops
  - _self_

centres_selection: median # options: mean, fmax, median
metric: cosine  # cosine,euclidean,iou
points_per_cluster: 1
adapt_to_crop_size: true